fix(coverage): Add files to be included or excluded during code coverage generation
atlp-rwanda/winners-c8-bn-be pull request #20
Opened 2022-06-09 16:52 UTC by nyakamwe

**What does this PR do?**
It fixes bugs related to code coverage status generation.

**Description of Task to be completed?**
- adding all js files found in src to be included
- exclude files from the test folder

**How should this be manually tested?**
After cloning this repo, add or remove some codes and run: npm run coverage
this will deliver a report to the coveralls and generate coverage status in percentage.

**What are the relevant pivotal tracker stories?**
#182209989

[coveralls #182209989]

2022-06-09 17:01 UTC, Himbaza123h commented
Well done!

2022-06-09 17:49 UTC, munezerobagira submitted a review, later dismissed

2022-06-09 18:22 UTC, munezerobagira reviewed
Checking  on coveralls the `src/sum.js` is only file which  has the coverage ,  you can increase the coverage to other files as well
https://coveralls.io/builds/49892434
![image](https://user-images.githubusercontent.com/42154315/172916626-c87f43f3-492a-411f-b2a0-fbf33ab1e312.png)
 make sure that other files like src/routes/index.js are checked too

2022-06-10 08:15 UTC, K-Ds commented on .nycrc.json
> +    "exclude": ["src/**/*.test.js", "src/database/migrations/*.js"]
You can also add **"src/database/seeders/*.js** to the list

2022-06-10 15:06 UTC, nyakamwe commented
The threshold is above 80% in local but when it comes to CI it decreases unexpectedly

2022-06-10 15:58 UTC, nyakamwe commented
> Checking on coveralls the `src/sum.js` is only file which has the coverage , you can increase the coverage to other files as well https://coveralls.io/builds/49892434 ![image](https://user-images.githubusercontent.com/42154315/172916626-c87f43f3-492a-411f-b2a0-fbf33ab1e312.png) make sure that other files like src/routes/index.js are checked too
![coveralls](https://user-images.githubusercontent.com/53573955/173105220-7fb225fd-8744-4842-9ffc-3b8aac122fe0.png)

2022-06-11 09:38 UTC, munezerobagira approved these changes

2022-06-11 09:38 UTC, munezerobagira commented on package.json
> +    "coverage": "nyc --reporter=text --reporter=lcov npm run test",
you can add the --all after nyc to collect  coverage for the entire project

2022-06-11 09:38 UTC, munezerobagira commented on .nycrc.json
> +    "exclude": ["src/**/*.test.js", "src/database/migrations/*.js"]
I am not sure if we will write the tests for seeders too, if possible you can add it  to exclude too

2022-06-11 09:38 UTC, munezerobagira commented on package.json
> +    "coverage": "nyc --reporter=text --reporter=lcov npm run test",
Or you can add it in .nycrc.json

2022-06-11 10:10 UTC, nyakamwe commented on package.json
> +    "coverage": "nyc --reporter=text --reporter=lcov npm run test",
yes, I have added it in .nycrc

2022-06-11 10:11 UTC, nyakamwe commented on .nycrc.json
> +    "exclude": ["src/**/*.test.js", "src/database/migrations/*.js"]
seeders are also excluded.

2022-06-13 07:48 UTC, denislohan requested changes
@nyakamwe ,
Your PR has conflicts

2022-06-13 19:43 UTC, habaumugisha1 approved these changes

2022-06-14 10:02 UTC, denislohan approved these changes

2022-06-14 10:02 UTC, merged